### ISSUE TITLE
Cursor opacity issue on some browsers.

### ISSUE THREAD

**Issue by VanLaerAshley** [stephenscaff/react-animated-cursor#3]
Cursor stays at opacity: 0 in other browsers than chrome on mac.

**Comment by stephenscaff** [comment]
Sorry - just noticed this.
Will take a look.
 
Do you have specifics?

**Comment by stephenscaff** [comment]
Fixed this by updating events  `mouseenter` -> `mouseover` and `mouseexit` -> `mouseout`. 

You can see the update <a href="https://github.com/stephenscaff/react-animated-cursor/blob/master/lib/AnimatedCursor.js#L91">here</a>.

Although, Safari is blurring the cursor scaling transition on hover/click. 
Have tried all the common ways to address this, none seem to work. 
Will need to explore this some more.
