### ISSUE TITLE
Demo link not working 

### ISSUE THREAD

**Issue by natainditama** [stephenscaff/react-animated-cursor#32]
Trying access https://stephenscaff.github.io/react-animated-cursor/ and then result page

![image](https://user-images.githubusercontent.com/81244669/208076893-21a2d323-5f97-4c27-8bcf-b7a7d16814a9.png)

**Comment by sagar-io** [comment]
Yes, It's not been fixed till now.
Is there any way I can see some live examples of this package?

**Comment by stephenscaff** [comment]
_Should_ be fixed now. 

I was using gh-pages to deploy the `/demo` directory via Parcel... which seems to have hiccuped. 

Gotta look into that futher. But, building off of master seems to work for now:

https://stephenscaff.github.io/react-animated-cursor/

Let me know if you don't see a working demo.

You can also pull down the repo and just run dev, which serves up the `/demo` directory with Parcel.

**Comment by stephenscaff** [comment]
Confirming demo works 

https://stephenscaff.github.io/react-animated-cursor/

 I've also included examples of how to create different cursors. Just used query params to update the component:

https://stephenscaff.github.io/react-animated-cursor/?cursor=blendmode
https://stephenscaff.github.io/react-animated-cursor/?cursor=default
https://stephenscaff.github.io/react-animated-cursor/?cursor=donut 


Closing this one. Reopen if you see any further issues.
