### ISSUE TITLE
System cursor not shown on clickables with `showSystemCursor` = `true`

### ISSUE THREAD

**Issue by Favo02** [stephenscaff/react-animated-cursor#39]

**Comment by stephenscaff** [comment]
Commented on your pr. 

To say again, should we roll your updates into the single `showSystemCursor` prop?
I'm thinking if you want cursor, you want it in all places?

Let me know if you have different thoughts.

**Comment by stephenscaff** [comment]
After some thought, fixed this by simply having showSystemCursor apply to clickables as well.

Thanks for your thoughts.
