### ISSUE TITLE
Support for server components nextjs

### ISSUE THREAD

**Issue by mpotane** [stephenscaff/react-animated-cursor#44]

**Comment by stephenscaff** [comment]
Thanks for bringing this up. 
Can you tell me a bit more?

If I understand things correctly, [looking at this chart](https://nextjs.org/docs/getting-started/react-essentials#when-to-use-server-and-client-components), a component like this _can't_ be a server component, as it has interactivity (`onMouseOver`, `onClick`, etc) and uses State and side effects (`useState()`, `useEffect()`).

Seems it needs to be Client Component (adding `'use client'` to top of file).

I have to do some experimenting with a new next build it seems. Did you have a repo / test case to share?

**Comment by mpotane** [comment]
Closing for now
