### ISSUE TITLE
Check if cursorOuterRef is null

### ISSUE THREAD

**Issue by IanDestura** [stephenscaff/react-animated-cursor#55]
![image](https://github.com/stephenscaff/react-animated-cursor/assets/108323133/566fe1af-28fc-4e04-be04-da0a0568ff61)

# Add condition to check if the cursorOuterRef is still define or not to avoid error in console
### A third-level heading

**Comment by stephenscaff** [comment]
Can you provide a bit more details on how you're producing this?

What's your config and environment look like?

I can't reproduce, but I also don't see any issues with your fix, so more than happy to add the check.

**Comment by stephenscaff** [comment]
So, turns out, this was a great callout and the issue went beyond your check. 

Used Next's linting config which exposed a few other errors/warnings that I addressed with #58 

About to merge that in and deploy to npm. Let me know if that fixes you issues.

Thanks.
