### ISSUE TITLE
Unsupported Server Component type: undefined, using Next.js 13 App router

### ISSUE THREAD

**Issue by alanvww** [stephenscaff/react-animated-cursor#56]
- error node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js (1684:8) @ attemptResolveElement
- error Error: Unsupported Server Component type: undefined
null
- error node_modules/next/dist/compiled/react-server-dom-webpack/cjs/react-server-dom-webpack-server.edge.development.js (1684:8) @ attemptResolveElement
- error Error: Unsupported Server Component type: undefined
![CleanShot 2023-09-18 at 23 22 25@2x](https://github.com/stephenscaff/react-animated-cursor/assets/10086000/417a86ed-ed8b-49fd-85f3-f9004f064d99)

**Comment by stephenscaff** [comment]
This is a very DOM-reliant FE/client component, it's not a server side component.
Next now has this notion of Client and Server Side components. 
With FE/Client components you have to add `'use client'` atop your file.

Not sure how this impacts 3rd party components. Will research right now and report back.

**Comment by stephenscaff** [comment]
So, i pushed a new version with use client defined. But getting Window is not defined issues still, so seems you still have to also load as dynamic import (per docs), but with "use client" defined also. So, probs the best way to do this now is to create a Cursor component locally like:

```
'use client'

import dynamic from 'next/dynamic';

const AnimatedCursor = dynamic(() => import('react-animated-cursor'), {
    ssr: false,
});

export default function Cursor() {
  return <AnimatedCursor/>
}
```

Then import that in your app or layout file.

Still researching other solutions.

**Comment by stephenscaff** [comment]
Hey again!

Just related `2.10.1` that has a bunch of updates around Next.js integration (and defining as a client component).

Now, you _should_ be able to rock a simple import, instead of a dynamic import. 

Give it a go, let me know. 

Will close this for now, but open it back up if you see any issues.

Thanks!
