### ISSUE TITLE
Cursor is not detecting mobile applications accurately.

### ISSUE THREAD

**Issue by nico-k3** [stephenscaff/react-animated-cursor#64]
Hi!
As the current solution for detecting a touch device is not really reliable and there are media queries like (hover:none) or (pointer: coarse) available, I would like to implement a better solution to activate / deactivate the cursor.

Currently I have to build a workaround on sites where I use this package, but I think this should be implemented into the core.

I will probably create a Pull Request shortly to make it happen.

**Comment by stephenscaff** [comment]
Approved your PR. Thanks for that. Will publish in a sec.
